### ISSUE TITLE
room for m3 / rubber feet

### ISSUE THREAD

**Issue by wovo** [CvRXX/myFirstDevBoard#2]

**Comment by CvRXX** [comment]
@wovo I need the dimensions for the rubber feet to change this. Can you put them on your desk tomorrow so I can take a few to measure them?

**Comment by CvRXX** [comment]
fixed by 696723d42228766d8a1a20b6e9d58cdf75adf79a

**Comment by CvRXX** [comment]
Reopened because the board is now to big for fabrication at the desired price range. We have to expend in vertical direction.

**Comment by CvRXX** [comment]
fixed with 70c8829129f8e52414bd638379cbc0dba544efa1
