### ISSUE TITLE
github url op onderkant

### ISSUE THREAD

**Issue by wovo** [CvRXX/myFirstDevBoard#4]

**Comment by CvRXX** [comment]
Waiting to fix this until I know how much space #2 is gonna free up.

**Comment by CvRXX** [comment]
fixed by 696723d42228766d8a1a20b6e9d58cdf75adf79a

**Comment by CvRXX** [comment]
Reopened because the board is now to big for fabrication at the desired price range. We have to expend in vertical direction.

**Comment by CvRXX** [comment]
fixed with 70c8829129f8e52414bd638379cbc0dba544efa1
